name: notepad
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  iconsax: ^0.0.8
   
  flutter_gen: ^5.8.0

  flutter_bloc: ^9.0.0

  bloc: ^9.0.0

  equatable: ^2.0.7
  flutter_hooks: ^0.21.2
  animations: ^2.0.11
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter 
  build_runner: ^2.4.13
  flutter_gen_runner: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Montaserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontaserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
     

flutter_gen: 
  output: lib/gen/
  integrations:
    flutter_svg: true 
